# Generated by Django 2.1.7 on 2019-03-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 Character <a href="https://www.isbn-internationa.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN'),
        ),
    ]
